apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-push-secret
  namespace: ${{ values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: quay-push-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"${{ values.image_host }}":{"auth":"{{ `{{ .auth }}` }}"}}}
  data:
    - secretKey: auth
      remoteRef:
        key: secrets/quay/auth
        property: value
