apiVersion: apps/v1
kind: Deployment
metadata:
  name: parasol-db
  namespace: ${{ values.namespace }}
  labels:
    app: parasol-db
    app.kubernetes.io/name: parasol-insurance-secured-${{ values.owner }}-${{ values.branch }}
    app.kubernetes.io/part-of: parasol-insurance-secured-dev
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parasol-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: parasol-db
        app.kubernetes.io/name: parasol-insurance-secured-${{ values.owner }}-${{ values.branch }}
        app.kubernetes.io/part-of: parasol-insurance-secured-dev
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: parasol-db
          image: registry.redhat.io/rhel8/postgresql-12:1
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: parasol-db
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: parasol-db
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: parasol-db
                  key: database-name
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            tcpSocket:
              port: 5432
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
                - /bin/sh
                - -i
                - -c
                - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
