kind: Secret
apiVersion: v1
metadata:
  name: parasol-db
  namespace: ${{ values.namespace }}
  labels:
    app.kubernetes.io/name: parasol-insurance-secured-${{ values.owner }}-${{ values.branch }}
    app.kubernetes.io/part-of: parasol-insurance-secured-dev
stringData:
  database-user: parasol
  database-password: parasol
  database-name: parasol
type: Opaque
