apiVersion: v1
kind: ServiceAccount
metadata:
  name: parasol-insurance-build
  namespace: ${{ values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: parasol-insurance-build-edit
  namespace: ${{ values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: parasol-insurance-build
    namespace: ${{ values.namespace }}
