apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rollout-restart
  namespace: ${{ values.namespace }}
spec:
  params:
    - name: DEPLOYMENT
      type: string
  steps:
    - name: rollout-restart
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      script: |
        #!/usr/bin/env bash
        oc rollout restart deployment/$(params.DEPLOYMENT)
        oc rollout status deployment/$(params.DEPLOYMENT) --timeout=300s
