apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: parasol-insurance-secured-push-binding
  namespace: ${{ values.namespace }}
spec:
  params:
    - name: git-revision
      value: $(body.checkout_sha)
